### ISSUE TITLE
Allow host/port to be defined programmatically or in pom.xml

### ISSUE THREAD

**Issue by arun-gupta** [ivargrimstad/snoop#8]
When multiple services are running in Docker, then host/port could vary with each run. Changing `application.yaml` will require the archive to be bundled again. It would be useful to provide host/port that can be either picked up programmatically or passed from `pom.xml`.

**Comment by arun-gupta** [comment]
Particularly, host/port of the application should not required to be defined in `application.yaml`. This could change all the time.

For example https://github.com/arun-gupta/microservices/blob/master/microservice/order/src/main/resources/application.yml#L3 require

```
snoop:
   applicationName: order
   applicationHome: http://localhost:8080/order/resources
   applicationServiceRoot: order
   serviceHost: 192.168.99.103:8081/snoop-service/
```

`applicationHome` should not be required here.
